### PR TITLE
fix small typo

### PR DESCRIPTION
**Pull request by fmichonneau**

### CODE REVIEW

**Comment by richfitz** [comment]
Legend, thanks :star2:

I'm going to do another documentation push soon - ideally as much as possible will be executable to avoid drift or typos like that..

**Comment by fmichonneau** [comment]
One thing I'd like to see in the doc is how you access the targets interactively.

I see there is now `make_environment()` but I find myself doing a lot of typing and there might be more efficient ways of doing it.

**Comment by richfitz** [comment]
Things to check out:

* `remake::make` returns the last target made
* `remake::fetch` can fetch any target value
* `remake::create_bindings` simulates running the project globally

I recognise that remake is currently not very user friendly - I'm still focussing on getting the underlying logic sorted out.  My hope is that a couple of different workflows can be built on top of the same engine.

**Comment by fmichonneau** [comment]
Exactly what I was missing. Thanks! :rainbow: :sunny: :star:

**Pull request merged**
