### PR TITLE
Test knitr targets in sub directory and via export script

### PR DESCRIPTION
**Pull request by dfalster**
NB - in the last commit, I took the approach of documenting the problem by writing a test. Currently that test fails. 

Does this approach work for you @richfitz? Main downside i see is that it leaves project in a state where it fails tests. Upside is test is written so easy to tell when issue is resolved.

### CODE REVIEW

**Comment by richfitz** [comment]
Yeah, pull requests seem like a nice way of illustrating problems like this that take a lot of files to get going.

**Comment by richfitz** [comment]
Ah, I see: this works OK for `remake` but doesn't work for the export script!

**Comment by dfalster** [comment]
Is this PR still in play, or should I cancel it? (reason for asking it that I may send another shortly)

**Comment by richfitz** [comment]
Whatever works for you.  Overhauling knitr support is on my list, but not super high up it.

**Pull request closed without merging**
